import * as admin from 'firebase-admin';

/**
 * Address Information
 * Represents a physical address with standard components.
 */
export interface Address {
  /** Street address line 1 */
  street: string;
  /** Street address line 2 (optional) */
  street2?: string;
  /** City */
  city: string;
  /** State or province */
  state: string;
  /** Postal/ZIP code */
  postalCode: string;
  /** Country (ISO 3166-1 alpha-2 code) */
  country: string;
}

/**
 * Insurance Information
 * Tracks patient insurance coverage for billing and eligibility verification.
 */
export interface InsuranceInfo {
  /** Insurance provider name */
  provider: string;
  /** Insurance plan type: Commercial, Medicare, Medicaid, or Self-Pay */
  type: 'commercial' | 'medicare' | 'medicaid' | 'self_pay';
  /** Member/subscriber ID */
  memberId: string;
  /** Group number (if applicable) */
  groupNumber?: string;
  /** Insurance policy effective date */
  effectiveDate?: admin.firestore.Timestamp;
  /** Insurance policy expiration date */
  expirationDate?: admin.firestore.Timestamp;
}

/**
 * Contact Information
 * Represents emergency contact or referral provider contact details.
 */
export interface ContactInfo {
  /** Contact person or provider name */
  name: string;
  /** Relationship to patient (e.g., "Spouse", "Referring Physician") */
  relationship: string;
  /** Contact phone number */
  phone?: string;
  /** Contact email address */
  email?: string;
}

/**
 * Patient
 * Core patient demographics and enrollment data.
 *
 * @remarks
 * PatientID and MRN are unique identifiers within a practice.
 * All personal identifiable information (PII) is protected by Firestore security rules.
 * EMR integration allows bi-directional sync of patient demographics.
 */
export interface Patient {
  /** Unique patient identifier (UUID, generated by system) */
  id: string;

  /** Practice ID - patient belongs to this practice (tenant) */
  practiceId: string;

  /** Medical Record Number - unique within practice */
  mrn: string;

  /** Patient first name */
  firstName: string;

  /** Patient last name */
  lastName: string;

  /** Patient date of birth */
  dateOfBirth: admin.firestore.Timestamp;

  /** Patient biological sex/gender for clinical context */
  sex: 'male' | 'female' | 'other' | 'unknown';

  /** Patient email address for contact and report delivery */
  email?: string;

  /** Patient phone number for SMS notifications and contact */
  phone?: string;

  /** Patient physical address for mail delivery */
  address?: Address;

  /** Insurance coverage information for billing */
  insurance?: InsuranceInfo;

  /** Emergency contact information */
  emergencyContact?: ContactInfo;

  /** Patient preferred language (ISO 639-1 code, e.g., "en", "es", "fr") */
  preferredLanguage: string;

  /** External EMR patient ID for integration synchronization */
  emrSourceId?: string;

  /** External EMR system identifier (Epic, Cerner, etc.) */
  emrSystem?: 'epic' | 'cerner' | 'allscripts' | 'manual';

  /** Flag indicating if patient record is archived/inactive */
  isArchived: boolean;

  /** Timestamp when patient record was created */
  createdAt: admin.firestore.Timestamp;

  /** Timestamp of last update to patient record */
  updatedAt: admin.firestore.Timestamp;

  /** User ID of clinician/staff who created the patient record */
  createdBy: string;
}
