import * as admin from 'firebase-admin';
import { ReportStatus, StudyType, DeliveryMethod, DraftSectionStatus, CodeSuggestionStatus } from './enums';

/**
 * Auto-Draft Section
 * Individual section auto-drafted by Copilot with linked evidence.
 * Defined in ZCW-BRD-0297.
 */
export interface AutoDraftSection {
  /** Section identifier (e.g., "clinical_impression", "recommendations") */
  id: string;
  /** Human-readable section title */
  title: string;
  /** Auto-drafted text content */
  content: string;
  /** Current status of section (pending review/accepted/edited/rejected) */
  status: DraftSectionStatus;
  /** Finding IDs linked as evidence for this section */
  linkedEvidence: string[]; // finding IDs
  /** Timestamp when section was drafted */
  draftedAt: admin.firestore.Timestamp;
  /** Clinician feedback or edits if modified/rejected */
  clinicianNotes?: string;
}

/**
 * Auto-Draft Report
 * Complete auto-drafted report generated by Copilot.
 * Defined in ZCW-BRD-0297.
 */
export interface AutoDraftReport {
  /** Timestamp when auto-draft was generated */
  generatedAt: admin.firestore.Timestamp;
  /** Copilot model version that generated the draft */
  modelVersion: string;
  /** Individual auto-drafted sections */
  sections: AutoDraftSection[];
  /** Overall acceptance status of auto-draft */
  acceptanceStatus: 'pending' | 'fully_accepted' | 'partially_accepted' | 'rejected';
}

/**
 * Code Entry
 * ICD-10 or CPT code with suggestion metadata.
 * Defined in ZCW-BRD-0299.
 */
export interface CodeEntry {
  /** Unique code identifier */
  id: string;
  /** ICD-10 or CPT code string */
  code: string;
  /** Human-readable description of code */
  description: string;
  /** Confidence score from AI suggestion (0-1.0) */
  confidence: number;
  /** Code acceptance status (suggested/confirmed/rejected) */
  status: CodeSuggestionStatus;
  /** Whether clinician has marked as favorite for reuse */
  isFavorite: boolean;
  /** Finding ID linked to this code if applicable */
  linkedFindingId?: string;
  /** Timestamp when code was added/suggested */
  addedAt: admin.firestore.Timestamp;
  /** Timestamp when code was confirmed/rejected */
  statusChangedAt?: admin.firestore.Timestamp;
}

/**
 * Risk Score
 * Clinical risk score based on findings and patient factors.
 * Examples: Crohn's severity score, polyp malignancy risk, etc.
 */
export interface RiskScore {
  /** Score type identifier (e.g., "lewis_score", "malignancy_risk") */
  scoreType: string;
  /** Human-readable score name for display */
  scoreName: string;
  /** Numeric score value */
  value: number;
  /** Score interpretation/category (e.g., "low", "moderate", "high") */
  interpretation: string;
  /** Explanation of how score was calculated */
  explanation?: string;
  /** Timestamp when score was calculated */
  calculatedAt: admin.firestore.Timestamp;
}

/**
 * Referral Entry
 * Referral recommendation based on findings.
 * Related to incidental findings workflow.
 */
export interface ReferralEntry {
  /** Unique referral identifier */
  id: string;
  /** Finding ID that triggered this referral */
  findingId: string;
  /** Type of referral (colonoscopy, specialty consult, etc.) */
  referralType: string;
  /** Recommended urgency of referral */
  urgency: string; // 'routine' | 'urgent' | 'emergent'
  /** Referral recommendation text */
  narrative: string;
  /** Whether referral is included in final report */
  includedInReport: boolean;
  /** Timestamp when referral was created */
  createdAt: admin.firestore.Timestamp;
}

/**
 * Supplemental Section
 * Report section for incidental findings outside primary focus.
 * Allows separate documentation of secondary findings.
 */
export interface SupplementalSection {
  /** Section identifier (e.g., "incidental_findings") */
  id: string;
  /** Section title */
  title: string;
  /** Section content */
  content: string;
  /** Finding IDs covered in this section */
  findingIds: string[];
  /** Display order in report */
  order: number;
  /** Timestamp when section was created */
  createdAt: admin.firestore.Timestamp;
  /** Timestamp of last update */
  updatedAt: admin.firestore.Timestamp;
}

/**
 * Delivery Record
 * Tracks report delivery to a recipient.
 * Records proof of delivery for compliance.
 */
export interface DeliveryRecord {
  /** Unique delivery record ID */
  id: string;
  /** Delivery method used */
  method: DeliveryMethod;
  /** Recipient email or identifier */
  recipient: string;
  /** Timestamp when delivery was initiated */
  deliveredAt: admin.firestore.Timestamp;
  /** Status of delivery (queued/sent/failed/confirmed) */
  status: 'queued' | 'sent' | 'failed' | 'confirmed';
  /** Error message if delivery failed */
  errorMessage?: string;
  /** Timestamp when delivery was confirmed by recipient (if applicable) */
  confirmedAt?: admin.firestore.Timestamp;
}

/**
 * Delivery Defaults
 * Practice-level defaults for report delivery.
 * Defined in ZCW-BRD-0298.
 */
export interface DeliveryDefaults {
  /** Default delivery methods for new reports */
  defaultMethods: DeliveryMethod[];
  /** Whether to auto-populate patient email if available */
  autoCheckPatientEmail: boolean;
  /** Whether to auto-populate referring physician email if available */
  autoCheckReferringEmail: boolean;
  /** Default cover letter text to include with delivery */
  defaultCoverLetter?: string;
  /** Recipient email addresses to always include */
  defaultRecipients: string[];
  /** Preferred report format (pdf, html, dicom_sr, etc.) */
  preferredFormat: 'pdf' | 'html' | 'dicom_sr';
}

/**
 * Report Section
 * Individual section of the final report body.
 */
export interface ReportSection {
  /** Section identifier */
  id: string;
  /** Section title */
  title: string;
  /** Section content (HTML or markdown) */
  content: string;
  /** Display order in report */
  order: number;
  /** Whether section should be included in PDF export */
  includeInExport: boolean;
  /** Timestamp when section was created/updated */
  updatedAt: admin.firestore.Timestamp;
}

/**
 * Simple Report Sections
 * Flat key-value format used for initial report drafts and seed data.
 * This is the format actually stored in Firestore for most reports.
 * The structured ReportSection[] format is used for finalized reports with ordering.
 */
export interface SimpleReportSections {
  findings: string;
  impression: string;
  recommendations: string;
  [key: string]: string; // Allow additional custom sections
}

/**
 * Report
 * Complete endoscopy report generated from a procedure.
 *
 * @remarks
 * Reports follow a state machine: draft → in_review → signed → (optionally) amended.
 * Reports can be auto-drafted by Copilot (ZCW-BRD-0297) or manually created.
 * Reports support multi-language generation and patient-facing translation.
 *
 * Defined in BRD Appendix B and referenced throughout ZCW-BRD requirements.
 */
export interface Report {
  /** Unique report identifier (UUID) */
  id: string;

  /** Procedure ID - the procedure this report documents */
  procedureId: string;

  /** Practice ID - practice that owns this report */
  practiceId: string;

  /** Patient ID - patient for this report */
  patientId: string;

  /** Clinician ID - clinician who authored/signed the report */
  clinicianId: string;

  /** Current status in report lifecycle */
  status: ReportStatus;

  /** Study type that determined report template */
  studyType: StudyType;

  // ========== AUTO-DRAFT ==========

  /** Auto-draft data if report was initially drafted by Copilot */
  autoDraft?: AutoDraftReport;

  // ========== REPORT CONTENT ==========

  /** Individual sections of the report body.
   * Can be either structured ReportSection[] for finalized reports
   * or SimpleReportSections for draft/seed data format. */
  sections: ReportSection[] | SimpleReportSections;

  // ========== CODES ==========

  /** ICD-10 diagnostic codes with suggestion metadata */
  icdCodes: CodeEntry[];

  /** CPT procedural codes with suggestion metadata */
  cptCodes: CodeEntry[];

  // ========== CLINICAL TEXT ==========

  /** Clinician's clinical impression and summary */
  clinicalImpression: string;

  /** Clinician recommendations for follow-up or treatment */
  recommendations: string;

  /** Recommended surveillance intervals if applicable */
  surveillanceRecommendations?: string[];

  /** Risk scores calculated for this patient (Lewis score, malignancy risk, etc.) */
  riskScores?: RiskScore[];

  // ========== THUMBNAILS ==========

  /** Strategy for including finding thumbnails in report */
  thumbnailMode: 'all_findings' | 'primary_only' | 'selected' | 'none';

  /** Finding IDs to include if thumbnailMode is 'selected' */
  selectedThumbnails: string[];

  // ========== REFERRALS ==========

  /** Referral recommendations based on findings */
  referrals: ReferralEntry[];

  // ========== SUPPLEMENTAL SECTIONS ==========

  /** Report sections for incidental findings outside primary focus */
  supplementalSections: SupplementalSection[];

  // ========== SIGNING ==========

  /** Timestamp when report was signed by clinician */
  signedAt?: admin.firestore.Timestamp;

  /** User ID of clinician who signed */
  signedBy?: string;

  /** Method used for signing (click/biometric/PIN) */
  signatureMethod: 'click' | 'biometric' | 'pin';

  // ========== DELIVERY ==========

  /** Delivery history for this report */
  deliveryRecords: DeliveryRecord[];

  /** Practice-level delivery defaults applied to this report */
  deliveryDefaults?: DeliveryDefaults;

  // ========== PDF EXPORTS ==========

  /** Storage path to clinician-facing PDF */
  pdfStoragePath?: string;

  /** Storage path to patient-facing translated/de-identified PDF */
  patientPdfStoragePath?: string;

  // ========== AUDIT & METADATA ==========

  /** Timestamp when report was created */
  createdAt: admin.firestore.Timestamp;

  /** Timestamp of last update to report */
  updatedAt: admin.firestore.Timestamp;
}

/**
 * Helper to extract section text from either format.
 * Handles both SimpleReportSections and ReportSection[] formats.
 */
export function getReportSectionText(sections: ReportSection[] | SimpleReportSections | undefined, sectionName: string): string {
  if (!sections) return '';
  // Simple format: { findings: '...', impression: '...', recommendations: '...' }
  if (!Array.isArray(sections)) {
    return (sections as SimpleReportSections)[sectionName] || '';
  }
  // Structured format: ReportSection[]
  const section = sections.find(s => s.id === sectionName || s.title?.toLowerCase() === sectionName.toLowerCase());
  return section?.content || '';
}
