/**
 * Capsule Image Pipeline Types
 *
 * TypeScript interfaces for the capsule endoscopy image pipeline.
 * The pipeline runs in a separate GCP project (podium-capsule-ingest)
 * and writes to the `capsule_images` Firestore collection in that project.
 *
 * ZoCW accesses this data via the `getCapsuleFrames` proxy Cloud Function.
 *
 * Data linkage: procedure.capsuleSerialNumber (ZoCW) = folder name in Storage
 * bucket = capsule_serial field in capsule_images collection.
 *
 * @see docs/IMAGE_PIPELINE_INTEGRATION.md for full architecture
 * @see docs/build-packets/BUILD_09_Image_Pipeline_Integration.md for build instructions
 */

import { AnatomicalRegion } from './enums';

// ============================================================================
// CEST ANATOMICAL LOCATIONS (AI Output Dictionary)
// ============================================================================

/**
 * CEST anatomical location strings as output by the Gemini 2.5 Flash AI model.
 * These are more granular than the clinician-facing AnatomicalRegion enum.
 * Stored as string literals because the AI dictionary may expand over time.
 */
export const CEST_ANATOMICAL_LOCATIONS = [
  'Upper Esophageal Sphincter (UES)',
  'Z-line',
  'Cardia',
  'Gastric Folds (Rugae)',
  'Antrum',
  'Pylorus',
  'Duodenal Bulb',
  'Major Papilla',
  'Jejunum (Prominent Circular Folds)',
  'Ileum (Diminished Folds)',
  'Ileocecal Valve',
  'Cecum / Appendiceal Orifice',
  'Haustra (Colon)',
  'Dentate Line',
] as const;

export type CestAnatomicalLocation = typeof CEST_ANATOMICAL_LOCATIONS[number];

// ============================================================================
// CEST FINDING CLASSIFICATIONS (AI Output Dictionary)
// ============================================================================

/**
 * CEST finding classification strings as output by the Gemini 2.5 Flash AI model.
 * These represent the full clinical vocabulary the AI uses to classify findings.
 */
export const CEST_FINDING_CLASSIFICATIONS = [
  // Normal / Non-pathological
  'Normal Clean Mucosa',

  // Luminal contents
  'Fresh Blood',
  'Hematin',
  'Chyme / Turbid Fluid',
  'Bile',
  'Mucus',
  'Food Residue / Fecal Loading',
  'Bubble Interference',

  // Mucosal changes
  'Erythema',
  'Edematous Mucosa',
  'Granular Mucosa',
  'Pale Mucosa',
  'Friable Mucosa',
  'Mosaic / Cobblestone Pattern',
  'Villous Atrophy / Scalloping',

  // Mucosal breaks
  'Mucosal Break - Erosion',
  'Mucosal Break - Ulcer',

  // Neoplastic / Mass lesions
  'Xanthoma',
  'Polyp',
  'Nodule',
  'Mass / Tumor',
  'Subepithelial Lesion',

  // Vascular
  'Angioectasia',
  'Phlebectasia',
  'Varices',
  'Lymphangiectasia',

  // Structural
  'Diverticulum',
  'Fistula',
  'Stricture',

  // Foreign / Parasitic
  'Parasite',
  'Foreign Body',
] as const;

export type CestFindingClassification = typeof CEST_FINDING_CLASSIFICATIONS[number];

// ============================================================================
// AI ANALYSIS RESULT
// ============================================================================

/**
 * AI analysis result produced by the `analyze-capsule-image` Cloud Function.
 * One result per frame, generated by Gemini 2.5 Flash at temperature 0.0.
 *
 * Every field uses CEST dictionary values (string literals) — not ZoCW enums.
 */
export interface AIAnalysisResult {
  /** Whether any anomaly was detected in this frame */
  anomaly_detected: boolean;

  /** Primary finding classification, null if normal mucosa */
  primary_finding: CestFindingClassification | null;

  /** Anatomical location identified in this frame */
  anatomical_location: CestAnatomicalLocation;

  /** Quality assessment of the mucosal view */
  mucosal_view_quality: string;

  /** AI confidence score for the primary finding (0.0 to 1.0) */
  confidence_score: number;

  /** Additional findings beyond the primary one */
  secondary_findings: CestFindingClassification[];

  /** Suggested bounding box for the finding (format TBD by AI model) */
  bounding_box_suggestion: string;

  /** Free-text clinical notes generated by the AI */
  clinical_notes: string;
}

// ============================================================================
// CAPSULE IMAGE DOCUMENT
// ============================================================================

/**
 * Firestore document schema for the `capsule_images` collection.
 * Lives in the pipeline project Firestore (podium-capsule-ingest).
 *
 * Created by `log-capsule-image` when frames are uploaded to Storage.
 * Updated by `analyze-capsule-image` when AI analysis completes.
 *
 * Field: `capsule_serial` = folder name in bucket = capsule serial number
 * scanned at check-in and stored as `procedure.capsuleSerialNumber` in ZoCW.
 *
 * NOTE: The deployed pipeline currently uses `procedure_id` as the field name.
 * This will be renamed to `capsule_serial` — see HANDOFF.md Priority 1B.
 */
export interface CapsuleImageDocument {
  /** Firestore document ID (auto-generated) */
  id?: string;

  /** Original filename of the frame image (e.g., "frame_00001.jpg") */
  filename: string;

  /**
   * Capsule serial number — the folder name from the Storage bucket.
   * Links to procedure.capsuleSerialNumber in ZoCW.
   *
   * NOTE: Field is currently named `procedure_id` in the deployed pipeline.
   * Will be renamed to `capsule_serial` — see HANDOFF.md Priority 1B.
   */
  capsule_serial: string;

  /** Storage bucket name (e.g., "podium-capsule-raw-images-test") */
  bucket: string;

  /** Full gs:// URL to the frame image in Cloud Storage */
  url: string;

  /** Processing status of this frame */
  status: 'pending' | 'processed' | 'error';

  /** AI analysis result — present when status === 'processed' */
  analysis?: AIAnalysisResult;
}

// ============================================================================
// RESPONSE TYPE FOR getCapsuleFrames CALLABLE
// ============================================================================

/**
 * Response shape from the `getCapsuleFrames` Cloud Function.
 * Returns the complete frame set + AI analysis for a given capsule serial.
 */
export interface GetCapsuleFramesResponse {
  /** Total number of frames in the capsule image set */
  totalFrames: number;

  /** Number of frames with completed AI analysis */
  analyzedFrames: number;

  /** Number of frames where AI detected an anomaly */
  anomalyFrames: number;

  /** The capsule serial number that was queried */
  capsuleSerial: string;

  /** All frame documents, ordered by filename ascending */
  frames: CapsuleImageDocument[];
}

// ============================================================================
// CEST → ZoCW ANATOMICAL REGION MAPPING
// ============================================================================

/**
 * Maps CEST anatomical location strings (from AI output) to the
 * clinician-facing AnatomicalRegion enum used throughout ZoCW UI.
 *
 * Multiple CEST locations can map to a single AnatomicalRegion.
 */
export const CEST_TO_ANATOMICAL_REGION: Record<CestAnatomicalLocation, AnatomicalRegion> = {
  'Upper Esophageal Sphincter (UES)': AnatomicalRegion.ESOPHAGUS,
  'Z-line': AnatomicalRegion.ESOPHAGUS,
  'Cardia': AnatomicalRegion.STOMACH,
  'Gastric Folds (Rugae)': AnatomicalRegion.STOMACH,
  'Antrum': AnatomicalRegion.STOMACH,
  'Pylorus': AnatomicalRegion.STOMACH,
  'Duodenal Bulb': AnatomicalRegion.DUODENUM,
  'Major Papilla': AnatomicalRegion.DUODENUM,
  'Jejunum (Prominent Circular Folds)': AnatomicalRegion.JEJUNUM,
  'Ileum (Diminished Folds)': AnatomicalRegion.ILEUM,
  'Ileocecal Valve': AnatomicalRegion.ILEUM,
  'Cecum / Appendiceal Orifice': AnatomicalRegion.CECUM,
  'Haustra (Colon)': AnatomicalRegion.COLON,
  'Dentate Line': AnatomicalRegion.RECTUM,
};

/**
 * Converts a CEST anatomical location to the ZoCW AnatomicalRegion enum.
 * Returns COLON as fallback if the location is unrecognized.
 */
export function cestToAnatomicalRegion(cestLocation: string): AnatomicalRegion {
  return CEST_TO_ANATOMICAL_REGION[cestLocation as CestAnatomicalLocation]
    ?? AnatomicalRegion.COLON;
}
