/**
 * Capsule Image Pipeline Types
 *
 * TypeScript interfaces for the capsule endoscopy image pipeline.
 * The pipeline runs in a separate GCP project (podium-capsule-ingest)
 * and writes to the `capsule_images` Firestore collection in that project.
 *
 * ZoCW accesses this data via the `getCapsuleFrames` proxy Cloud Function.
 *
 * Data linkage: procedure.capsuleSerialNumber (ZoCW) = capsule_id field
 * in the pipeline's capsule_images collection = subfolder name in GCS bucket.
 *
 * Pipeline Firestore schema (v7.0.0, 3-tier):
 *   Document ID: {batch_id}_{capsule_id}_{filename}
 *   Fields: batch_id, capsule_id, filename, bucket, url, status, created_at, analysis
 *   GCS path: gs://{bucket}/{batch_id}/{capsule_id}/{filename}
 *
 * @see docs/BUILD_09_GAP_ANALYSIS.md for field mapping (Finding 11: 3 doc generations)
 * @see docs/BUILD_09_IMPLEMENTATION_PLAN.md for build instructions
 */

import { AnatomicalRegion } from './enums';

// ============================================================================
// CEST ANATOMICAL LOCATIONS (AI Output Dictionary)
// ============================================================================

/**
 * CEST anatomical location strings as output by the Gemini 2.5 Flash AI model.
 * These are more granular than the clinician-facing AnatomicalRegion enum.
 * Stored as string literals because the AI dictionary may expand over time.
 */
export const CEST_ANATOMICAL_LOCATIONS = [
  'Upper Esophageal Sphincter (UES)',
  'Z-line',
  'Cardia',
  'Gastric Folds (Rugae)',
  'Antrum',
  'Pylorus',
  'Duodenal Bulb',
  'Major Papilla',
  'Jejunum (Prominent Circular Folds)',
  'Ileum (Diminished Folds)',
  'Ileocecal Valve',
  'Cecum / Appendiceal Orifice',
  'Haustra (Colon)',
  'Dentate Line',
] as const;

export type CestAnatomicalLocation = typeof CEST_ANATOMICAL_LOCATIONS[number];

// ============================================================================
// CEST FINDING CLASSIFICATIONS (AI Output Dictionary)
// ============================================================================

/**
 * CEST finding classification strings as output by the Gemini 2.5 Flash AI model.
 * These represent the full clinical vocabulary the AI uses to classify findings.
 */
export const CEST_FINDING_CLASSIFICATIONS = [
  // Normal / Non-pathological
  'Normal Clean Mucosa',

  // Luminal contents
  'Fresh Blood',
  'Hematin',
  'Chyme / Turbid Fluid',
  'Bile',
  'Mucus',
  'Food Residue / Fecal Loading',
  'Bubble Interference',

  // Mucosal changes
  'Erythema',
  'Edematous Mucosa',
  'Granular Mucosa',
  'Pale Mucosa',
  'Friable Mucosa',
  'Mosaic / Cobblestone Pattern',
  'Villous Atrophy / Scalloping',

  // Mucosal breaks
  'Mucosal Break - Erosion',
  'Mucosal Break - Ulcer',

  // Neoplastic / Mass lesions
  'Xanthoma',
  'Polyp',
  'Nodule',
  'Mass / Tumor',
  'Subepithelial Lesion',

  // Vascular
  'Angioectasia',
  'Phlebectasia',
  'Varices',
  'Lymphangiectasia',

  // Structural
  'Diverticulum',
  'Fistula',
  'Stricture',

  // Foreign / Parasitic
  'Parasite',
  'Foreign Body',
] as const;

export type CestFindingClassification = typeof CEST_FINDING_CLASSIFICATIONS[number];

/**
 * IMAGE QUALITY classifications — findings that describe viewing conditions
 * rather than clinical pathology. Used to split the Findings panel into
 * "Clinical Findings" (actionable) vs "Image Quality" (informational).
 *
 * TEMPORARY (Option A): Hardcoded from the CEST taxonomy above.
 * TARGET (Option B): Replace with `finding_category: 'clinical' | 'image_quality'`
 * field in the pipeline AIAnalysisResult schema, so the AI model assigns
 * the category at analysis time. See HANDOFF.md backlog item.
 */
export const IMAGE_QUALITY_CLASSIFICATIONS: ReadonlySet<string> = new Set([
  'Normal Clean Mucosa',
  'Chyme / Turbid Fluid',
  'Bile',
  'Mucus',
  'Food Residue / Fecal Loading',
  'Bubble Interference',
]);

/** Returns true if a finding classification is an image quality indicator, not clinical pathology */
export function isImageQualityFinding(classification: string): boolean {
  return IMAGE_QUALITY_CLASSIFICATIONS.has(classification);
}

// ============================================================================
// AI ANALYSIS RESULT
// ============================================================================

/**
 * AI analysis result produced by the `analyze-capsule-image` Cloud Function.
 * One result per frame, generated by Gemini 2.5 Flash at temperature 0.0.
 *
 * Every field uses CEST dictionary values (string literals) — not ZoCW enums.
 */
export interface AIAnalysisResult {
  /** Whether any anomaly was detected in this frame */
  anomaly_detected: boolean;

  /** Primary finding classification, null if normal mucosa */
  primary_finding: CestFindingClassification | null;

  /** Anatomical location identified in this frame */
  anatomical_location: CestAnatomicalLocation;

  /** Quality assessment of the mucosal view */
  mucosal_view_quality: string;

  /** AI confidence score for the primary finding (0.0 to 1.0) */
  confidence_score: number;

  /** Additional findings beyond the primary one */
  secondary_findings: CestFindingClassification[];

  /** Suggested bounding box for the finding (format TBD by AI model) */
  bounding_box_suggestion: string;

  /** Free-text clinical notes generated by the AI */
  clinical_notes: string;
}

// ============================================================================
// CAPSULE IMAGE DOCUMENT
// ============================================================================

/**
 * Firestore document schema for the `capsule_images` collection.
 * Lives in the pipeline project Firestore (podium-capsule-ingest).
 *
 * Created by `log-capsule-image` when frames are uploaded to Storage.
 * Updated by `analyze-capsule-image` when AI analysis completes.
 *
 * v7.0.0 schema (3-tier):
 *   Document ID: {batch_id}_{capsule_id}_{filename} (deterministic composite)
 *   capsule_id = capsule serial number = ZoCW linkage key
 *   batch_id = YYYYMMDD upload date grouping (irrelevant for ZoCW queries)
 *
 * Note: Older documents (Gen 1/Gen 2) may lack batch_id/capsule_id fields
 * or use the legacy `procedure_id` field. The getCapsuleFrames query
 * (`WHERE capsule_id == X`) only matches Gen 3 (v7.0.0) documents.
 * See docs/BUILD_09_GAP_ANALYSIS.md Finding 11 for details.
 */
export interface CapsuleImageDocument {
  /** Firestore document ID (deterministic: {batch_id}_{capsule_id}_{filename}) */
  id?: string;

  /** Original filename of the frame image (e.g., "00008430.bmp") — used for ordering */
  filename: string;

  /** Upload batch date grouping (YYYYMMDD or test name) — not used for ZoCW queries */
  batch_id: string;

  /**
   * Capsule serial number — the primary linkage key between pipeline and ZoCW.
   * Matches procedure.capsuleSerialNumber in ZoCW Firestore.
   * Query: WHERE capsule_id == procedure.capsuleSerialNumber
   */
  capsule_id: string;

  /** Legacy field from pre-v7.0.0 pipeline. Only present on Gen 2 docs. Do NOT query on this. */
  procedure_id?: string;

  /** Storage bucket name (e.g., "podium-capsule-raw-images-test") */
  bucket: string;

  /** Full gs:// URL to the frame image in Cloud Storage */
  url: string;

  /** Processing status of this frame */
  status: 'pending' | 'processed' | 'error';

  /** Pipeline creation timestamp */
  created_at?: any;

  /** AI analysis result — present when status === 'processed' */
  analysis?: AIAnalysisResult;
}

// ============================================================================
// RESPONSE TYPE FOR getCapsuleFrames CALLABLE
// ============================================================================

/**
 * Response shape from the `getCapsuleFrames` Cloud Function.
 * Returns the complete frame set + AI analysis for a given capsule serial.
 */
export interface GetCapsuleFramesResponse {
  /** Total number of frames in the capsule image set */
  totalFrames: number;

  /** Number of frames with completed AI analysis */
  analyzedFrames: number;

  /** Number of frames where AI detected an anomaly */
  anomalyFrames: number;

  /** The capsule serial number that was queried */
  capsuleSerial: string;

  /** All frame documents, ordered by filename ascending */
  frames: CapsuleImageDocument[];
}

// ============================================================================
// CEST → ZoCW ANATOMICAL REGION MAPPING
// ============================================================================

/**
 * Maps CEST anatomical location strings (from AI output) to the
 * clinician-facing AnatomicalRegion enum used throughout ZoCW UI.
 *
 * Multiple CEST locations can map to a single AnatomicalRegion.
 */
export const CEST_TO_ANATOMICAL_REGION: Record<CestAnatomicalLocation, AnatomicalRegion> = {
  'Upper Esophageal Sphincter (UES)': AnatomicalRegion.ESOPHAGUS,
  'Z-line': AnatomicalRegion.ESOPHAGUS,
  'Cardia': AnatomicalRegion.STOMACH,
  'Gastric Folds (Rugae)': AnatomicalRegion.STOMACH,
  'Antrum': AnatomicalRegion.STOMACH,
  'Pylorus': AnatomicalRegion.STOMACH,
  'Duodenal Bulb': AnatomicalRegion.DUODENUM,
  'Major Papilla': AnatomicalRegion.DUODENUM,
  'Jejunum (Prominent Circular Folds)': AnatomicalRegion.JEJUNUM,
  'Ileum (Diminished Folds)': AnatomicalRegion.ILEUM,
  'Ileocecal Valve': AnatomicalRegion.ILEUM,
  'Cecum / Appendiceal Orifice': AnatomicalRegion.CECUM,
  'Haustra (Colon)': AnatomicalRegion.COLON,
  'Dentate Line': AnatomicalRegion.RECTUM,
};

/**
 * Converts a CEST anatomical location to the ZoCW AnatomicalRegion enum.
 * Returns COLON as fallback if the location is unrecognized.
 */
export function cestToAnatomicalRegion(cestLocation: string): AnatomicalRegion {
  return CEST_TO_ANATOMICAL_REGION[cestLocation as CestAnatomicalLocation]
    ?? AnatomicalRegion.COLON;
}
